# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "TIL"

# A description of your site for meta tag, search engine results.
description: "Hi there! Welcome to my TIL blog."

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: /tech-blog

# The base hostname & protocol of your site for where absolute urls are needed.
url: clytaemnestra.github.io


# Profile settings
author:
  name: Mia Bajic # author name
  github: clytaemnestra # github username
  # linkedin: mia-bajic # linkedin username
  email: miabajic.miabajic@gmail.com # email adress
  avatar: images/author.png # change with your own avatar


# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  # - text: Archieve
  #   url: /archieve
  # - text: About 
  #   url: /about
  # - text: Style Guide
  #   url: /style-guide/
  - text: Tags
    url: /tags
  # - text: Download
  #   url: https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme

# The shortname for your Disqus site to enable comments.
# disqus: justgoodthemes

# Colors
accent_color: '#6B8EB7'

# Site footer
footer:
  # content: "&copy; Scriptor all rights reserved. Theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

jekyll-archives:
  enabled: []
  layout: default
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'


# http://jekyllrb.com/docs/pagination/
paginate: 20
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
